### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jsejcksn** [obi1kenobi/jester#4]
Are you still using this or do you use something like Authy? Also, do you have active plans to develop further or is this in an as-is/archived status?

**Comment by obi1kenobi** [comment]
I'm not really using this anymore -- most places now support 2FA natively, either via the TOTP protocol or at least via texts, so there's little need to do password-change tricks anymore. I don't have active plans to develop this further -- though if you'd like to take it over, you are welcome to it and I am happy to answer any questions you might have.
